title: Rodrigo S. Pereira
logo: /assets/img/me2.png
description: > 
  <br>
  I am a Data Scientist and Mechanical Engineer with a foundation in statistical analysis, programming in Python and R, and exploratory data analysis. 
  I have worked on problems supported by data-driven approaches, using machine learning algorithms and creating visualizations to communicate insights to stakeholders. 
  <br><br>
  <a href="https://www.linkedin.com/in/rspsabino/">View my LinkedIn Profile</a>

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
